import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { routing } from './app.routing';
import { AppComponent } from './app.component';
import { GroupListComponent } from './group-list/group-list.component';
import { DataService } from './service/data.service';
import { AccordionModule,
   AutoCompleteModule,
   BreadcrumbModule,
   ButtonModule,
   CalendarModule,
   CarouselModule,
   ChartModule,
   CheckboxModule,
   CodeHighlighterModule,
   SharedModule,
   ContextMenuModule,
   DataGridModule,
   DataListModule,
   DataScrollerModule,
   DataTableModule,
   DialogModule,
   ConfirmDialogModule,
   DragDropModule,
   DropdownModule,
   EditorModule,
   FieldsetModule,
   FileUploadModule,
   GalleriaModule,
   GMapModule,
   GrowlModule,
   InputMaskModule,
   InputSwitchModule,
   InputTextModule,
   InputTextareaModule,
   LightboxModule,
   ListboxModule,
   MegaMenuModule,
   MenuModule,
   MenubarModule,
   MessagesModule,
   MultiSelectModule,
   OrderListModule,
   OverlayPanelModule,
   PaginatorModule,
   PanelModule,
   PanelMenuModule,
   PasswordModule,
   PickListModule,
   ProgressBarModule,
   RadioButtonModule,
   RatingModule,
   ScheduleModule,
   SelectButtonModule,
   SlideMenuModule,
   SliderModule,
   SpinnerModule,
   SplitButtonModule,
   TabMenuModule,
   TabViewModule,
   TerminalModule,
   TieredMenuModule,
   ToggleButtonModule,
   ToolbarModule,
   TooltipModule,
   TreeModule,
   TreeTableModule,
   TriStateCheckboxModule,
   BlockUIModule
} from 'primeng/primeng';
import { TeamListComponent } from './team-list/team-list.component';
import { TeamMemeberComponent } from './team-memeber/team-memeber.component';


@NgModule({
  declarations: [
    AppComponent,
    GroupListComponent,
    TeamListComponent,
    TeamMemeberComponent
  ],
  imports: [
    BrowserModule,
    BrowserModule,
    FormsModule,
    HttpModule,
    ReactiveFormsModule,
    routing,
    BrowserAnimationsModule,
    AccordionModule,
       AutoCompleteModule,
       BreadcrumbModule,
       ButtonModule,
       CalendarModule,
       CarouselModule,
       ChartModule,
       CheckboxModule,
       CodeHighlighterModule,
       SharedModule,
       ContextMenuModule,
       DataGridModule,
       DataListModule,
       DataScrollerModule,
       DataTableModule,
       DialogModule,
       ConfirmDialogModule,
       DragDropModule,
       DropdownModule,
       EditorModule,
       FieldsetModule,
       FileUploadModule,
       GalleriaModule,
       GMapModule,
       GrowlModule,
       InputMaskModule,
       InputSwitchModule,
       InputTextModule,
       InputTextareaModule,
       LightboxModule,
       ListboxModule,
       MegaMenuModule,
       MenuModule,
       MenubarModule,
       MessagesModule,
       MultiSelectModule,
       OrderListModule,
       OverlayPanelModule,
       PaginatorModule,
       PanelModule,
       PanelMenuModule,
       PasswordModule,
       PickListModule,
       ProgressBarModule,
       RadioButtonModule,
       RatingModule,
       ScheduleModule,
       SelectButtonModule,
       SlideMenuModule,
       SliderModule,
       SpinnerModule,
       SplitButtonModule,
       TabMenuModule,
       TabViewModule,
       TerminalModule,
       TieredMenuModule,
       ToggleButtonModule,
       ToolbarModule,
       TooltipModule,
       TreeModule,
       TreeTableModule,
       TriStateCheckboxModule,
       BlockUIModule
  ],
  providers: [DataService],
  bootstrap: [AppComponent]
})
export class AppModule { }
